### ISSUE TITLE
Any more updates?

### ISSUE THREAD

**Issue by Y-T-G** [LutingWang/awesome-knowledge-distillation-for-object-detection#2]
There's been a couple of new papers in the topic.

**Comment by LutingWang** [comment]
This update includes a new survey paper in the field. I reviewed the CVPR 2023 paper list but did not come across any relevant publications. Although there are several papers on KD for 3D detection, this repository is presently focused on 2D detection, so they have not been included. If you happen to come across any excellent papers that I have missed, please let me know.

**Comment by Y-T-G** [comment]
@LutingWang I came [CrossKD](https://github.com/jbwang1997/CrossKD) with promising results. Although, it is still a pre-print.

**Comment by Y-T-G** [comment]
There's also [Dual Relation Knowledge Distillation for Object Detection](https://arxiv.org/abs/2302.05637) claiming SoTA although they don't compare with some of the more recent works.

**Comment by LutingWang** [comment]
Thanks for the recommendation! I've added the papers to the list.

**Comment by Y-T-G** [comment]
I came across [Task-Balanced Distillation for Object Detection](https://paperswithcode.com/paper/task-balanced-distillation-for-object) which is also a great paper with several novel innovations.

Also the CVPR 2023 paper [ScaleKD](https://openaccess.thecvf.com/content/CVPR2023/html/Zhu_ScaleKD_Distilling_Scale-Aware_Knowledge_in_Small_Object_Detector_CVPR_2023_paper.html) seems to be relevant, even though the target was SOD, because they compared with other KD methods for 2D object detection.

**Comment by LutingWang** [comment]
Added :smile:
